### ISSUE TITLE
page: SectionPage with References for canonical link

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/tapir#149]
## What

Currently only the `Article` has a `References` with the canonical link. For SEO reasons we also need this on all section pages.

## Proposal

```diff
message SectionPage {
   repeated Stage stages = 1;
+  References references = 2;
}

message ArticlePage {
   stroeer.core.v1.Article article = 1;
   repeated RelatedArticle related_articles = 2;
+  References references = 3; // because of same logic for `Pages` in FE
}
```

The only downside of this is that the `Article` and `ArticlePage` has the same `References` (duplication).

**Comment by thisismana** [comment]
Because Slack is async, a summary of the previous discussion:

##### Downsides of this proposal:
- `references` would be duplicated: `ArticlePage.references` and also in `ArticlePage.article.references`
    - the first one exists only for the symmetry toward `SectionPage`
    - the later one exists to allow proper linking of `Teasers` (which are also of type `Article`)

##### Other approach:

Similar to the current hierarchy: `ArticlePage.article.references` we would add a `SectionPage.section.references` by introducing a new `PageItem` of type `Section` (similar to `Article`). This would hold the relevant information such as `references` and `section_data` required for canonical and breadcrumb).

```diff
message SectionPage {
+   Section section = 1;
-   repeated Stage stages = 1;
-   repeated Stage stages = 2;
}

message Article {
...
// requires a new name.
-   Section section = 5;
+   SectionTree sectionTree = 5; 
}

+ message Section {
+    SectionTree sectionTree = 1; 
+    References references = 2;
+ }

```
