### ISSUE TITLE
conventional commits

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/tapir#3]
## Proposal

https://www.conventionalcommits.org/en/v1.0.0/

## Example

```
feat(node): add esm bundle
feat(proto): add new model
ci: use ubuntu-latest
```

## Why

https://www.conventionalcommits.org/en/v1.0.0/#why-use-conventional-commits

**Comment by harryurban** [comment]
main usage for these conventional commits is IMHO to generate nice release texts (changelog), for now we are not creating releases, but since this is a open source project, I still agree we should write good commit messages, but since PRs are squashed the PR title is more important than the invidivial commit messages.

**Comment by moritzzimmer** [comment]
Release notes can be generated automatically now, https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes so 👍 for this

**Comment by moritzzimmer** [comment]
we could validate this for PRs using https://github.com/amannn/action-semantic-pull-request
